// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyProductAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.1";
    }
}
