// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("3.0.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.0.0-beta.2+4.Branch.release-3.0.0.Sha.aacafedda5ba9ebeb760f281908b6e6545ba970f")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0.0";
    }
}
