// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Cronus.Transport.RabbitMQ")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("2.2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.2.0+0.Branch.master.Sha.3dd330e280aad323793004940f7f61e52428ef52")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.2.0.0";
    }
}
