name: Add issue/PR to project
on: [issues, pull_request]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-prs-to-development
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.gh_auto_projects }}
        GITHUB_PROJECT_URL: https://github.com/orgs/Elders/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Development
    - name: add-new-issues-to-styx
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.gh_auto_projects }}
        GITHUB_PROJECT_URL: https://github.com/orgs/Elders/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Styx
